### ISSUE TITLE
Ros2 Rolling has a breaking Pose2D msgs

### ISSUE THREAD

**Issue by geoeo** [Kukanani/vision_msgs_proposal#70]
Im so confused.

I just upgraded to ros2 rolling on a machine and my Pose2D msgs is different from galactic. The reason why I am opening this here is that according to the path, the Pose2D reference is on vison_msgs not in geometry_msgs

New:
```
`class Pose2D(metaclass=Metaclass_Pose2D):
    """Message class 'Pose2D'."""

    __slots__ = [
        '_position',
        '_theta',
    ]

    _fields_and_field_types = {
        'position': 'vision_msgs/Point2D',
        'theta': 'double',
    }
```

As you can see this class has a position element which wraps x,y. These two values are supposed to be inline? Where does this come from. I cant see the change in the Humble branch?

**Comment by SteveMacenski** [comment]
We did indeed add a new Pose2D message to this project starting in v4.0.0 which should be in Humble and Rolling (I checked too, it is released to both, but I can't speak if its been synced yet).

We did this based on feedback of abuse of that message time and because the plan is to deprecate the geometry_msgs version of it. While it is API the same, yes, it is in a new location so from a code auto-gen perspective, there is a change

**Comment by geoeo** [comment]
I see, so this is intended and known that this breaks interfaces to galactic?

**Comment by SteveMacenski** [comment]
~Yeah~

Well it shouldn't have broken mid-distribution, right? its a break from Galactic moving forward into Humble/Rolling. If it was broken mid-distribution, we need to work on ABI policies for this repo so that we dont have breaking changes mid-release

**Comment by geoeo** [comment]
Alright. I just have to have strange catches in our code while we migrate to rolling/humble. Thanks!
