### ISSUE TITLE
displaying results of vision_msgs

### ISSUE THREAD

**Issue by RoeschFlo** [Kukanani/vision_msgs_proposal#96]
I am sorry, but how can i display a topic of the type: vision_msgs?
If i use: rostopic echo /yolov7/yolov7
I get a wild bunch of numbers.
If i use: rostopic echo /yolov7/yolov7/result
WARNING: topic [/yolov7/yolov7/result] does not appear to be published yet

There is nothing to display.

**Comment by Kukanani** [comment]
I don't think your problem is specific to this repository. In fact, I'm not even sure if your yolov7 node is publishing vision_msgs, you might be subscribing raw image data instead. Either way, getting more details about each message depends on the message type that's being published. Another good idea is probably to use a tool like [this one](https://github.com/NovoG93/vision_msgs_rviz_plugins) which can show you the results in RViz.
